// <auto-generated />
using Game.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication_Jogo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221024173434_AdicionadoColunaTabela_PosicoesEmPartida")]
    partial class AdicionadoColunaTabela_PosicoesEmPartida
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("WebApplication_Jogo.Entity.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoPartida")
                        .HasColumnType("TEXT");

                    b.Property<string>("JogadorDaVezConnectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("WebApplication_Jogo.Entity.Partida", b =>
                {
                    b.OwnsOne("WebApplication_Jogo.Entity.Jogador", "JogadorFora", b1 =>
                        {
                            b1.Property<int>("PartidaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorFora_ConnectionIdd");

                            b1.Property<string>("Marca")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorFora_Nome");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.OwnsOne("WebApplication_Jogo.Entity.Jogador", "JogadorLocal", b1 =>
                        {
                            b1.Property<int>("PartidaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ConnectionId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorLocal_ConnectionIdd");

                            b1.Property<string>("Marca")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorLocal_Nome");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.OwnsOne("WebApplication_Jogo.Entity.Tabuleiro", "Tabuleiro", b1 =>
                        {
                            b1.Property<int>("PartidaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Posicoes")
                                .HasColumnType("TEXT")
                                .HasColumnName("Tabuleiro_Posicoes");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.Navigation("JogadorFora");

                    b.Navigation("JogadorLocal");

                    b.Navigation("Tabuleiro");
                });
#pragma warning restore 612, 618
        }
    }
}
