// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Dados;

#nullable disable

namespace WebApplication_Jogo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Web.Model.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoPartida")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Web.Model.Partida", b =>
                {
                    b.OwnsOne("Web.Model.Jogador", "JogadorFora", b1 =>
                        {
                            b1.Property<int>("PartidaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorFora_ConnectionIdd");

                            b1.Property<string>("Nome")
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorFora_Nome");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.OwnsOne("Web.Model.Jogador", "JogadorLocal", b1 =>
                        {
                            b1.Property<int>("PartidaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ConnectionId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorLocal_ConnectionIdd");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("JogadorLocal_Nome");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.Navigation("JogadorFora");

                    b.Navigation("JogadorLocal");
                });
#pragma warning restore 612, 618
        }
    }
}
